name = "checkcrpto"
type = "webpack"
account_id = "Festusmbahcloud@gmail.com"
workers_dev = false

[site]
bucket = "./public"
entry-point = "workers-site"

[[routes]]
  pattern = "/submit_email"
  script = "workers-site"
